public class Q1RegenerateAndSoeted {
//    You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:
//
//    b[0] is equal to a[0];
//    b[1] is equal to the last element of a;
//    b[2] is equal to a[1];
//    b[3] is equal to the second-last element of a;
//    b[4] is equal to a[2];
//    b[5] is equal to the third-last element of a;
//    and so on.
//    Your task is to determine whether the new array b is sorted in strictly ascending order or not.
//
//    Here is how the process of generating the new array b works:
    boolean solution(int[] a) {
        int[] b = new int[a.length];
        int lo = 0;
        int hi = a.length - 1;
        for (int i = 0; i < a.length; i++) {
            if (i % 2 == 0) {
                b[i] = a[lo++];
            } else {
                b[i] = a[hi--];
            }
        }
        for (int i = 1; i < b.length; i++) {
            if (b[i] <= b[i - 1]) {
                return false;
            }
        }
        return true;
    }
}
